### ISSUE TITLE
Add support for feline.nvim

### ISSUE THREAD

**Issue by siduck** [Pocco81/true-zen.nvim#65]
https://github.com/famiu/feline.nvim

**Comment by Pocco81** [comment]
TrueZen has kind of like a "global statusline handler" and AFAIK feline.nvim works well with it... Or isn't?

**Comment by siduck76** [comment]
> TrueZen has a "global statusline handler" and AFAIK feline.nvim works well with it... Or doesn't it?

it works good but I see this line on the top! 

![image](https://user-images.githubusercontent.com/59060246/135091426-e9dcd72d-ab48-4462-a57f-7e93c5bdd024.png)

**Comment by Pocco81** [comment]
Hello! please check #84.
