### ISSUE TITLE
Ataraxis mode hides the neovim vanilla statusline but doesn't bring it back 

### ISSUE THREAD

**Issue by ayushnix** [Pocco81/true-zen.nvim#74]
When I switch on the Ataraxis mode, the statusline at the bottom (vanilla statusline that ships with neovim) gets hidden. However, when I switch off Ataraxis mode, the status line doesn't come back and stays hidden. No changes have been made to the default configuration and `:TZAtaraxis` is activated using `<Leader>z`. TrueZen has been installed as an optional plugin using packer. The neovim version is `0.6.1`.

Before switching on Ataraxis mode:

![swappy-20220128_012944](https://user-images.githubusercontent.com/79408161/151434716-6629416e-d065-4266-a08b-4940ba68549d.png)

While  Ataraxis mode is switched on:
![swappy-20220128_012957](https://user-images.githubusercontent.com/79408161/151434741-38ab147b-1cac-46cd-bfce-58668847711c.png)

After switching off Ataraxis mode: 
![swappy-20220128_013011](https://user-images.githubusercontent.com/79408161/151434761-4ebcc82a-be53-42ba-ad3a-df5b27fae7ff.png)

**Comment by ProDeSquare** [comment]
If you type `: help statusline` you can see the default status line is set to empty. To make it stay you can set your own status line. Below is an example of how I dealt with this issue.

`vim.opt.statusline = " %f%=%y %{&fileencoding?&fileencoding:&encoding}[%{&fileformat}] %l,%c %p%% "`

**Comment by xarthurx** [comment]
Same issue using `feline` for statusline.

It would be super helpful if the plugin can read what was the status before activating it, and restore it afterwards.

Relying on the user to define the `statusline` is not very user-friendly and require advanced knowledge for the user.

**Comment by Pocco81** [comment]
Hello! please check #84.
