### ISSUE TITLE
Issues exiting any TrueZen mode with Lua colorscheme.

### ISSUE THREAD

**Issue by YuCao16** [Pocco81/true-zen.nvim#75]
Sorry to border you, I have a similar Issue as #66 .

For `lua` base colorscheme Plug, such as [github-nvim-theme](https://github.com/projekt0n/github-nvim-theme), [material.nvim](https://github.com/marko-cerovac/material.nvim), `highlight StatusLineNC ctermfg=bg ctermbg=bg guibg=bg guifg=bg` will throw `E420 BG color unknown`. However, `material.nvim` works totoally fine but `github-nvim-theme` I got below Error:
```
E5108: Error executing lua ...ue-zen/services/modes/mode-ataraxis/modules/hi_group.lua:136: Vim:E492: Not an editor command
:  guifg=Cyan        
                                                                                                 
stack traceback:                                                                                                           
        [C]: in function 'cmd'                                                                                             
        ...ue-zen/services/modes/mode-ataraxis/modules/hi_group.lua:136: in function 'restore_hi_groups' 
        ...im/lua/true-zen/services/modes/mode-ataraxis/service.lua:490: in function 'off'                                 
        ....nvim/lua/true-zen/services/modes/mode-ataraxis/init.lua:127: in function 'off'                                 
        ....nvim/lua/true-zen/services/modes/mode-ataraxis/init.lua:149: in function 'toggle'                              
        ....nvim/lua/true-zen/services/modes/mode-ataraxis/init.lua:159: in function 'main'                                
        ...nvim/autoload/plugged/TrueZen.nvim/lua/true-zen/main.lua:29: in function 'main'                                 
        [string ":lua"]:1: in main chunk
```
If trying to re-enter TZAtaraxis mode, the neovim would exit without any message.

I have tried [solution in #66 ](https://github.com/Pocco81/TrueZen.nvim/issues/66#issuecomment-942275480) but still get above Error. 

**I mean this seems like a `github-nvim-theme` issue, but is there anything I can do apart from ask `github-nvim-theme`?**

ps. I really enjoy this Plugin, really helpful!

**Comment by tim-hilt** [comment]
Just installed this plugin and I noticed the same issue very fast. I also use github-nvim-theme.

**Comment by Pocco81** [comment]
Hello! please check #84.
