### ISSUE TITLE
ataraxia does not hide vimairline

### ISSUE THREAD

**Issue by citosid** [Pocco81/true-zen.nvim#76]
Hello there!

First of all, excelent job with this tool! I'm loving it!!!

---

![image](https://user-images.githubusercontent.com/201430/174418426-6bd12360-8689-4842-ad8f-08a0d3a6a5c6.png)

As can be seen in the image, ataraxia does not hide some part of the vimairline status bar in the top. 

This is how it looks after toggling out of it:

![image](https://user-images.githubusercontent.com/201430/174418478-c5298676-ae1b-49ce-af3b-91126b19d8de.png)

And after changing the buffer with `:bn` this is how it looks:

![image](https://user-images.githubusercontent.com/201430/174418497-8057e668-4827-4741-8127-a65187f8840e.png)

It seems is really the bottom bar that goes to the top and then remains there.

---------

Another issue but not sure if it is related is I'm using tmux, and the screen does not reload after the tmux split changes sizes:

![image](https://user-images.githubusercontent.com/201430/174418562-7f9c3b94-d0d7-466f-a3c3-b56d209122c0.png)

you can see the width of the usable area is bigger than the tmux split

**Comment by Pocco81** [comment]
Hello! please check #84.
