### ISSUE TITLE
Toggle on specific filetype

### ISSUE THREAD

**Issue by Arrow-x** [Pocco81/true-zen.nvim#78]
So I want to use TrueZen only with vimwiki, so I have this autocammand
``` lua
vim.api.nvim_create_autocmd("FileType", {
	pattern = "vimwiki",
	callback = function()
		vim.cmd("TZAtaraxis")
	end,
})
```
but as you might guess it will flipflop between opening and not, I want to know if there is a way to know if true zen is open or not

**Comment by FOSSilizedDaemon** [comment]
> So I want to use TrueZen only with vimwiki, so I have this autocammand
> 
> ```lua
> vim.api.nvim_create_autocmd("FileType", {
> 	pattern = "vimwiki",
> 	callback = function()
> 		vim.cmd("TZAtaraxis")
> 	end,
> })
> ```
> 
> but as you might guess it will flipflop between opening and not, I want to know if there is a way to know if true zen is open or not

Does it work with

´´´
vim.cmd("TZAtaraxisOn")
´´´

**Comment by Arrow-x** [comment]
No not at all, it just mess up my markdown conceal level for some reason.

**Comment by FOSSilizedDaemon** [comment]
> No not at all, it just mess up my markdown conceal level for some reason.

I am also having issues with markdown, but for different reasons. I am unsure what could be causing this.

**Comment by Pocco81** [comment]
Hello! please check #84.
