### ISSUE TITLE
TrueZen Does not Quit When Used in Markdown Files and Shows Status Line in Markdown Files When laststatus=0

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [Pocco81/true-zen.nvim#82]
I am having two issues with this plugin. The first issue is that I have the following settings:

    true_zen.setup({
        modes = {
            ataraxis = {
                -- Instead of toggling TrueZen, for some reason,
                -- just quit when commands like "q" are used.
                quit = nil,
            },
        },
    })

This setting has worked as expected for every filetype, except markdown files. I am unsure why this is the case. I have tried a fresh install of neovim with only truezen and just this configuration, but still have this issue.

The second issue is that, for some reason, truezen always shows a statusline on the top of the window when in markdown files. I have tried disabled my statusline before turning on truezen, uninstalling my statusline, etc. but nothing works.

**Comment by Pocco81** [comment]
Hello! please check #84.
