### ISSUE TITLE
[Feature Request] Winbar Support

### ISSUE THREAD

**Issue by shaunsingh** [Pocco81/true-zen.nvim#85]
Hi, loving the plugin even more after the rewrite

Currently I have one small issue: my winbar still shows in `:TZAtaraxis` mode. 

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/71196912/181877195-e32aa46e-7cbd-4537-b845-6cc9ffc3fcce.png">

Is this something that you would like to implement in true-zen? If not I completely understand, I can do it with an auto command as well. Just thought I should let you no first

**Comment by Pocco81** [comment]
Sure! No problem :)

Mind sharing the autocmd/snippet you are currently using to hide the WinBar?

**Comment by Pocco81** [comment]
Done :tada:

**Comment by mehalter** [comment]
I can also verify that there are still winbars on all the scratch windows
