### ISSUE TITLE
Unexpected callback behaviour

### ISSUE THREAD

**Issue by georgijd** [Pocco81/true-zen.nvim#88]
Hi, great plugin!

I noticed an unexpected callback behaviour as I defined callback functions for all modes. Upon entering/exiting the `narrow` mode I'm seeing the callbacks for `narrow`, `ataraxis` and `minimalist` modes being executed. I suppose that's because `narrow` mode invokes `ataraxis` which in turn invokes `minimalist`. One way to fix this is to parameterize the `on()` and `off()` functions and introduce a flag to skip callbacks.

**Comment by Pocco81** [comment]
> Upon entering/exiting the narrow mode I'm seeing the callbacks for narrow, ataraxis and minimalist modes being executed. I suppose that's because narrow mode invokes ataraxis which in turn invokes minimalist

Yes, if you have the setting for displaying the narrowed text inside an Ataraxia session then yes: Narrow invokes Ataraxis, which in turn calls minimalist.

> One way to fix this is to parameterize the on() and off() functions and introduce a flag to skip callbacks

Could you elaborate? I have an idea for how to go about this, however I would like to know what you think first :)

Also, perhaps #87 is relevant for this issue too.

**Comment by georgijd** [comment]
I am suggesting to change the API with something along the lines of

```lua
function M.on(opts)
	...
	if opts.skip_callbacks then
		data.do_callback("minimalist", "open")
	end
	...
end
```

instead of 

```lua
function M.on()
        ...
	data.do_callback("minimalist", "open")
        ...
end
```

**Comment by Pocco81** [comment]
Nice implementation. However let's think about scenarios where _we'd want_ the callbacks from each mode to be executed... In this case the implementation above wouldn't work, no?

I suggest maybe adding global vars for each mode that get evaled when it's their time to run.

Something like:

```lua
...
-- my truezen conf for narrow mode 
open_callback = function ()
    vim.g.true_zen_minimalist_callbacks = false
    -- do something
end
...
```

And then in minimalist mode check if their callbacks are disabled. If so then ignore it and set the var above to true.

I could push this to the `dev` branch to test things out.

**Comment by georgijd** [comment]
Yes, something like that would work.

What might be even better is to expose functions which return whether a mode is active, e.g.

```lua
require('true-zen.ataraxis').is_on()
```

One could then use this function in the callback function for `minimalist` and act accordingly. For example:

```lua
truezen.setup({
  modes = {
    ...
    minimalist = {
      open_callback = function()
        if not require('true-zen.ataraxis').is_on() then
          -- do something
        end
      end,
    },
    ...
  },
})
```

**Comment by Pocco81** [comment]
See https://github.com/Pocco81/true-zen.nvim#callbacks and https://github.com/Pocco81/true-zen.nvim#api
