### ISSUE TITLE
Exiting narrow mode with :q doesn't open folds

### ISSUE THREAD

**Issue by oncomouse** [Pocco81/true-zen.nvim#90]
With the default settings, if I open narrow mode and then exit the Atraxis session using `:q`, the folds set by narrow mode remain closed. This might be the intended behavior but with `fold_style = "invisible"`, it scared the pants off me (looked like the rest of my file had vanished). In either case, it's a bit annoying as implemented and might be worth looking into a fix for.

**Comment by oncomouse** [comment]
This is fixable using options passed to `setup()`:

~~~
local augroup = nil
require("true-zen").setup({
modes = {
	ataraxis = {
		open_callback = function()
			augroup = vim.api.nvim_create_augroup("dotfiles-settings-true-zen", {})
			vim.api.nvim_create_autocmd("QuitPre", {
				group = augroup,
				callback = function()
					if vim.b.tz_narrowed_buffer then
						vim.schedule(function()
							vim.cmd([[normal! zE]])
						end)
					end
				end,
			})
		end,
		close_callback = function()
			vim.api.nvim_del_augroup_by_id(augroup)
		end,
	},
},
})
~~~

But it might be worth fixing in the Ataraxis code itself.

**Comment by oncomouse** [comment]
It's also worth noting that if you exit narrow mode using `:q` and then run `:TZNarrow` again, Neovim quits.

**Comment by Pocco81** [comment]
I made it so that if `run_atarxis = true` on narrow's conf and `quit_untoggles = true` on ataraxis' conf then `quit` will also untoggle the current narrowed buf.
