### ISSUE TITLE
Feature: imrprove ataraxis mode

### ISSUE THREAD

**Issue by kaiphat** [Pocco81/true-zen.nvim#94]
Thank you for great plugin!

But i would to say how i see perfect zen mode:)
When i open ataraxis mode i have one window which has width equals default_width from config.
When i open vertical split i have two windows, every has default_width and orientired by center. If screen_width < 2 * default_width, then window width will be less than default_width.

**Comment by Pocco81** [comment]
sorry but could elaborate on what the problem is, exactly?

**Comment by kaiphat** [comment]
How ataraxis works now:
- full screen [ 100 ]
- ataraxis [ padding 30 | width 40 | padding 30 ]
- make vertical split  [ padding 30 | width 20 | width 20 | padding 30 ]

How i would be:
- full screen [ 100 ]
- ataraxis [ 30 | default_width 40 | 30 ]
- make vertical split  [ 10 | default_width 40 | default_width 40 | 10 ]
- make vertical split  [ width 33 | width 33 | width 33 ]

**Comment by oblitum** [comment]
@kaiphat you could try camspiers/lens.vim to handle this with more flexibility and smarter.
