### ISSUE TITLE
`'statusline'` not hidden in Ataraxis mode

### ISSUE THREAD

**Issue by loqusion** [Pocco81/true-zen.nvim#99]
First, just want to say the lualine integration is working perfectly for me :)

However, when I enter Ataraxis mode the vanilla statusline is still visible. (I disabled lualine and the integration to isolate the issue.) To confirm:

- `'statusline'` is empty (`""`)
- The highlight groups `StatusLine` and `StatusLineNC` are cleared

Setting `'statusline'` to a single space character (`" "`) instead of just blank hides the status line for me, perhaps it's a viable solution?

<img width="1034" alt="Screen Shot 2022-08-06 at 11 38 03 PM" src="https://user-images.githubusercontent.com/38332081/183275524-8d541f8a-ce48-46c9-ad23-9e8a99449f12.png">

**Comment by Pocco81** [comment]
should be working now :tada:
